server:
  port: 8095
spring:
  application:
    name: msvc-chatbot
  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?useSSL=false&serverTimezone=UTC
    username: root
    password: admin10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect