server:
  port: 8095
spring:
  application:
    name: msvc-chatbot
  datasource:
    url: jdbc:mysql://localhost:3306/service_product
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka