server:
  port: 8095

spring:
  application:
    name: msvc-chatbot

  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 250520
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15  # Aumentado para servicio de chatbot que puede tener alta concurrencia
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: ChatbotHikariPool
      leak-detection-threshold: 60000  # Detección de conexiones perdidas

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        generate_statistics: true
        use-new-id-generator-mappings: true
    open-in-view: false

  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  redis:  # Configuración adicional para posible uso de caché
    host: localhost
    port: 6379
    password:
    timeout: 5000

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.msvc.chatbot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai: DEBUG  # Para integración con IA/chatbots

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    metadata-map:
      version: 1.0
      zone: primary
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, httptrace
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: db, diskSpace, redis, eureka
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: true

# Configuración específica para chatbot
chatbot:
  max-conversation-history: 10
  timeout-seconds: 30
  default-language: es