server:
  port: 8120

spring:
  application:
    name: search-service

auction:
  service:
    url: http://localhost:8085

product:
  service:
    url: http://localhost:8105
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka