# ======= SERVER CONFIG ========
server:
  port: 8115
  forward-headers-strategy: framework

spring:
  spring:
    application:
      name: microservice-user
    config:
      activate:
        on-profile: default
  webflux:
    base-path: /

  # ======= DATABASE CONFIG ========
  datasource:
    url: jdbc:mysql://localhost:3306/db_usuarios?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 250520
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ======= JPA/HIBERNATE ========
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # ======= OAUTH2 GOOGLE ========
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 761498102570-2l6q4psf63uk2t0l3g4gb41bajd0kpld.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile,openid
            redirect-uri: http://localhost:8081/usuarios/login/oauth2/callback/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: name

  # ======= EMAIL CONFIG ========
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # ======= APPLICATION CONFIG ========
  application:
    name: servicio-usuarios
  cloud:
    gcp:
      core:
        enabled: false
    config:
      enabled: false

# ======= JWT CONFIG ========
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 horas en milisegundos

# ======= FRONTEND URL ========
app:
  frontend:
    url: http://localhost:3000
    login-success-redirect: http://localhost:3000/login-success
    login-failure-redirect: http://localhost:3000/login-failed
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: '*'
    allow-credentials: true

# ======= EUREKA DISCOVERY (SERVICE REGISTRY) ========
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}