<<<<<<< HEAD
spring:
  application:
    name: msvc-simulator
  config:
    import: optional:configserver:http://localhost:8888
=======
server:
  port: 8110

spring:
  application:
    name: microservice-simulator
  config:
    activate:
      on-profile: default
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/simulator_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 250520
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
>>>>>>> 0b8f0e8a544e38ad0823415f396cc1a3421fd1f3
