spring.application.name=microservice-simulator

# PUERTO DEL CHAT
server.port=8110

# PARA MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/simulator_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.application.name=microservice-simulator
spring.cloud.config.enabled=false

