server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  main:
    web-application-type: reactive
    cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-auction
          uri: 'http://localhost:8085'
          predicates:
            - Path=/api/auctions/**
            - Path=/api/auction-history/**
        - id: microservice-bid
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/bids/**
        - id: microservice-chatbot
          uri: 'http://localhost:8095'
          predicates:
            - Path=/api/chat/**
            - Path=/api/ping/**
        - id: microservice-payment
          uri: 'http://localhost:8100'
          predicates:
            - Path=/api/transactions/**
        - id: microservice-product
          uri: 'http://localhost:8105'
          predicates:
            - Path=/api/products/**
        - id: microservice-simulator
          uri: 'http://localhost:8110'
          predicates:
            - Path=/api/simulator/**
        - id: microservice-user
          uri: 'http://localhost:8115'
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
            - Path=/oauth2/**
        - id: microservice-search
          uri: 'http://localhost:8120'
          predicates:
            - Path=/api/search**


eureka:
  client:
    register-with-eureka: false